const staticImagesPath =
  "https://d2ivesio5kogrp.cloudfront.net/static/watcho/images/";

export const ImageConfig = {
  logo: staticImagesPath + "logo.svg",
  mobilelogo: staticImagesPath + "logo.svg",
  defaultbanner: staticImagesPath + "default-banner.png",
  defaultdetails: staticImagesPath + "default-details.png",
  defaultMoviePoster: staticImagesPath + "default-movie-poster.png",
  lazyimage16x9: staticImagesPath + "default-details.png",

  bottomLayout: {
    favoriteActive: staticImagesPath + "favorite-active.svg",
    favorite: staticImagesPath + "heart.svg",
    share: staticImagesPath + "share.svg",
  },

  card: {
    favoriteActive: staticImagesPath + "favorite-active.svg",
    favorite: staticImagesPath + "heart.svg",
    share: staticImagesPath + "share.svg",
    watchlistSelected: staticImagesPath + "watchlist-selected.svg",
    watchlistWhite: staticImagesPath + "watchlist-white.svg",
    shareWhite: staticImagesPath + "share-white.svg",
    kingCore: staticImagesPath + "king-core-latest.svg",
    threeDots: staticImagesPath + "three-dots.svg",
    userUnFollow: staticImagesPath + "user-unfollow.svg",
    rightArrowWhite: staticImagesPath + "arrow-right-white.svg",
    userFollow: staticImagesPath + "user-follow-icon.svg",
    checkMark: staticImagesPath + "checkmark.svg",
  },

  changePassword: {
    arrowBack: staticImagesPath + "arrow-back.svg",
  },

  footer: {
    androidTv: staticImagesPath + "multi-device-android-tv.png",
    fireTv: staticImagesPath + "new-fire-tv-icon.png",
    lGTv: staticImagesPath + "multi-device-lg.png",
    samsungTv: staticImagesPath + "multi-device-samsung.png",
    appleTv: staticImagesPath + "multi-device-apple-tv.png",
    iosDevice: staticImagesPath + "multi-device-ios-2.png",
    androidDevice: staticImagesPath + "multi-device-android-mobile.png",
    dishtv: staticImagesPath + "dishtv-logo.png",
    dth: staticImagesPath + "d2h-logo.png",
    tizen: staticImagesPath + "new-multi-device-samsung.png",
    webOS: staticImagesPath + "new-multi-device-webos.png",
  },

  socialIcons: {
    facebook: staticImagesPath + "ott-facebook-follow.svg",
    instagram: staticImagesPath + "ott-instagram-follow.svg",
    twitter: staticImagesPath + "ott-twitter-follow.svg",
    youtube: staticImagesPath + "ott-youtube-follow.svg",
    linkedin: staticImagesPath + "share-linkedin-follow.svg",
    pintrest: staticImagesPath + "share-pintrest-follow.svg",
    whatsapp: staticImagesPath + "whatsapp.png",
  },
  sharePopUp: {
    facebook: staticImagesPath + "share-facebook-follow.svg",
    twitter: staticImagesPath + "share-twitter-follow.svg",
    linkedin: staticImagesPath + "share-linkedin-follow.svg",
    pintrest: staticImagesPath + "share-pintrest-follow.svg",
    whatsapp: staticImagesPath + "whatsapp.png",
  },
  desktopHeader: {
    headerFilter: staticImagesPath + "header-filter.svg",
    languageSelectionIcon: staticImagesPath + "language-selection-icon.svg",
    headerAbout: staticImagesPath + "header-about.svg",
    lockIcon: staticImagesPath + "lock-icon.svg",
    headerMailSupport: staticImagesPath + "header-support-mail.svg",
    searchIcon: staticImagesPath + "search-icon.svg",
    profileImage: staticImagesPath + "profile-pic1.svg",
    aboutus: staticImagesPath + "header-about.svg",
    becomeOurPartner: staticImagesPath + "handshake-icon.svg",
    swagCreator: staticImagesPath + "bxs_video_plus.png",
  },

  mobileHeader: {
    searchIcon: staticImagesPath + "search_icon_new.svg",
    swagCreatorM: staticImagesPath + "Become_a_Fliqs_Creator.png",
    becomeOurPartner: staticImagesPath + "handshake-icon.svg",
    notification_icon: staticImagesPath + "notification_icon.svg",
    Subscribe_btn_mobile: staticImagesPath + "Subscribe_btn_mobile.svg",
    Upgrade_btn_mobile: staticImagesPath + "upgrade_btn_mobile.svg",
    Renew_btn_mobile: staticImagesPath + "Renew_btn_mobile.svg",
    Dishtvone_star_icon: staticImagesPath + "Dishtvone_star_icon.svg",
  },

  PageLoader: {
    loader: staticImagesPath + "loadingicon.png",
  },
  packages: {
    back: staticImagesPath + "back.svg",
  },
  mbDwnldHeader: {
    closeIcon: staticImagesPath + "lan-popup-close.png",
    appStore: staticImagesPath + "app_store.svg",
    playStore: staticImagesPath + "google_play.svg",
  },
  myAccount: {
    helpBackArrow: staticImagesPath + "help-back-arrow.svg",
    defaultProfilePic: staticImagesPath + "profile-pic1.svg",
    lockIcon: staticImagesPath + "lock-icon.svg",
    userProfilePic: staticImagesPath + "user-profile-pic1.svg",
    searchIcon: staticImagesPath + "search-icon.svg",
    myAccountIocn: staticImagesPath + "myaccount_icon.svg",
    myAccountArrow: staticImagesPath + "myaccount_arrow.svg",
    myAccountBlackArrow: staticImagesPath + "myaccount_black_arrow.svg",
    myaccountSubscribe: staticImagesPath + "myaccount_subscribe_icon.svg",
    myaccountUpgrade: staticImagesPath + "myaccount_upgrade_icon.svg",
    myaccountRenew: staticImagesPath + "myaccount_renew_icon.svg",
  },
  checkOut: {
    payLock: staticImagesPath + "pay-lock.png",
  },
  payments: {
    paymentSuccess: staticImagesPath + "payment-success-n.svg",
    subscriptionSuccessful: staticImagesPath + "subscribed-sucessfully.svg",
    hugeIconCouponMobile: staticImagesPath + "mob-hugeicons-coupon-percent.svg",
    exchangeIcon: staticImagesPath + "exchange-icon.svg",
    noPurchaseVideo: staticImagesPath + "no-purchase-video.png",
    paymentFailure: staticImagesPath + "payment-failure.svg",
    tickIcon_freedomtv: staticImagesPath + "tickIcon_freedomtv.svg",
    tickIcon_freedomtv_Black: staticImagesPath + "tick-icon-white.svg",
  },
  pageNotFound: {
    noFavourites: staticImagesPath + "no-fav.svg",
    emptyCart: staticImagesPath + "empty-cart.png",
    back: staticImagesPath + "back.svg",
    errorImage: staticImagesPath + "error-img.png",
    contentnotFound: staticImagesPath + "Content-not-found-image.png",
  },
  jwPlayer: {
    helpBackArrow: staticImagesPath + "help-back-arrow.svg",
    forwardIcon: staticImagesPath + "forward-10.svg",
  },
  support: {
    helpBackArrow: staticImagesPath + "help-back-arrow.svg",
  },
  playerDescription: {
    favoriteActive: staticImagesPath + "favorite-active.svg",
    favorite: staticImagesPath + "heart.svg",
    share: staticImagesPath + "share.svg",
    imdb: staticImagesPath + "imdb.png",
    plusGray: staticImagesPath + "plus-gray.svg",
    search: staticImagesPath + "search-svg-icon.svg",
    shareIcon: staticImagesPath + "share-svg-icon.svg",
    report: staticImagesPath + "report.svg",
    likeGray: staticImagesPath + "like-thin-gray.svg",
    solarEye: staticImagesPath + "solar-eye-linear.svg",
    likeFillWhite: staticImagesPath + "like-fill-white.svg",
    watchedTick: staticImagesPath + "watched-tick-mark.svg",
  },
  search: {
    searchIcon: staticImagesPath + "search-icon.svg",
  },
  popup: {
    closeIcon: staticImagesPath + "lan-popup-close.png",
    selectedEmoji: staticImagesPath + "emoji_selected.png",
    swagIconPink: staticImagesPath + "swag-icon-pink.svg",
  },
  packages: {
    back: staticImagesPath + "help-back-arrow.svg",
  },
  subscriptionModal: {
    paymentSuccess: staticImagesPath + "payment-failure.svg",
    paymentFailure: staticImagesPath + "payment-success-icon.svg",
  },
  profile: {
    editProfile: staticImagesPath + "edit-profile.svg",
    lockIcon: staticImagesPath + "lock-icon.svg",
    addProfile: staticImagesPath + "add_profile_icon.svg",
    back: staticImagesPath + "back.svg",
    premiumDiamond: staticImagesPath + "premium-diamond.svg",
    manage_profile_icon : staticImagesPath + "manage_profile_icon.svg",
    login_success_icon : staticImagesPath + "login_success_icon.svg"
  },
  viewRestrictions: {
    parentalLock: staticImagesPath + "parental-lock.svg",
    closeIcon: staticImagesPath + "lan-popup-close.png",
    back: staticImagesPath + "back.svg",
  },
  countryDropDown: {
    closeIcon: staticImagesPath + "lan-popup-close.png",
    dropdownIcon : staticImagesPath + "country_dropdown_icon.svg"
  },
  shorts: {
    mute: staticImagesPath + "mute.png",
    unmute: staticImagesPath + "un-mute.png",
    dishtv_mute: staticImagesPath + "short_mute.svg",
    dishtv_unmute: staticImagesPath + "short_unmute.svg",
    short_mobile_Unmute: staticImagesPath + "short_mobile_Unmute.svg",
    short_mobile_Mute: staticImagesPath + "short_mobile_Mute.svg",
    play: staticImagesPath + "play.png",
    pause: staticImagesPath + "pause.png",
    dishTv_play: staticImagesPath + "short_play.svg",
    dishTv_pause: staticImagesPath + "short_pause.svg",
    dishTv_share: staticImagesPath + "short_share.svg",
    mob_dishTv_share: staticImagesPath + "short_mobile_share.svg",
    web_short_like: staticImagesPath + "short_LikeIcon.svg",
    web_short_liked: staticImagesPath + "short_LikeIcon.svg",
    mob_short_like: staticImagesPath + "like-thin-gray.svg",
    mob_short_liked: staticImagesPath + "favorite-active.svg",
    back_arrow: staticImagesPath + "help-back-arrow.svg",
    short_mobile_Pause: staticImagesPath + "short_mobile_Pause.svg",
    short_mobile_Play: staticImagesPath + "short_mobile_Play.svg",
    short_close: staticImagesPath + "short_close.svg",
    ThreeDotsShorts: staticImagesPath + "three-dots-shorts.svg",
    solarEyeShorts: staticImagesPath + "solar-eye-short.svg",
    solarEyeShortsM: staticImagesPath + "mob-solar-eye-shorts.svg",
    ShortLiked: staticImagesPath + "short-like-icon-active.svg",
    short_like_mob: staticImagesPath + "shorts-like-mobile.svg",
    shortLikeFill: staticImagesPath + "short_like_gray_active.svg",
  },
  socialLogins: {
    apple: staticImagesPath + "apple-login-icon.svg",
    facebook: staticImagesPath + "facebook-logo.png",
    google: staticImagesPath + "google-icon.png",
  },
  settings: {
    lockIcon: staticImagesPath + "lock-icon.svg",
    back: staticImagesPath + "back.svg",
  },
  sections: {
    back: staticImagesPath + "arrow-back.svg",
  },
  tvGuide: {
    rightArrow: staticImagesPath + "right-arrow.svg",
    leftArrow: staticImagesPath + "left-arrow.png",
  },
  tvShowDetails: {
    imdb: staticImagesPath + "imdb.png",
    trailerIcon: staticImagesPath + "trailer-icon-web.svg",
    favoriteActive: staticImagesPath + "favorite-active.svg",
    favorite: staticImagesPath + "heart.svg",
    share: staticImagesPath + "share.svg",
    watchlistSelected: staticImagesPath + "watchlist-selected.svg",
    watchlistWhite: staticImagesPath + "watchlist-white.svg",
    shareWhite: staticImagesPath + "share-white.svg",
    packageInfo: staticImagesPath + "pack-info-icon.svg",
    helpBackArrow: staticImagesPath + "help-back-arrow.svg",
    playCirclebtn: staticImagesPath + "play-circle-outline.svg",
  },
  bookd2h: {
    back: staticImagesPath + "help-back-arrow.svg",
    reactangle: staticImagesPath + "Rectangle2183.png",
  },
};
